---
title: "ICMPS lab tidy"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readr)
```

```{r, warning=FALSE, message=FALSE}
icpms_data <- read.csv("~/Chem 313 lab/ICMPS lab/Soil_data/ICPMS_Data.csv", skip = 1,
                          na="N/A")

sample_key <- read.csv("~/Chem 313 lab/ICMPS lab/Soil_data/Sample_Key.csv", skip = 0)
#preview
icpms_data
sample_key
```

#tidy time
```{r, warning=FALSE, message=FALSE}
rsd_data<- icpms_data%>%
  select(Cr52 =CPS.RSD,
         Cr53= CPS.RSD.1, 
         As75= CPS.RSD.2,
         Cd111= CPS.RSD.3,
         Cd114 = CPS.RSD.4,
         PB208= CPS.RSD.5,
         Ge_RSD = CPS.RSD.7,
         Sample.Key)%>%
  pivot_longer(1:6,
               names_to  = "metal",
               values_to ="RSD")

```

```{r, warning=FALSE, message=FALSE}
icpms_tidy<- icpms_data%>%
  select(Cr52 =CPS,
         Cr53= CPS.1, 
         As75= CPS.2,
         Cd111= CPS.3,
         Cd114 = CPS.4,
         PB208= CPS.5,
         Ge72 = CPS.7,
         Sample.Key)%>%
  pivot_longer(1:6,
               names_to  = "metal",
               values_to ="CPS")%>%
  mutate(RSD = rsd_data$RSD/rsd_data$Ge_RSD,
         CPS=CPS/Ge72)%>%
  select(-Ge72)

```


```{r, warning=FALSE, message=FALSE}
icpms_merged<- merge(icpms_tidy, sample_key)

icpms_merged

```








